### ISSUE TITLE
Potential perf improvements

### ISSUE THREAD

**Issue by boguscoder** [Tw1ddle/geometrize-lib#1]
Hi
First of all, thanks for great open source library! 

Are there any performance tests or any other tests that you'd recommend running before proposing any silly perf optimizations?

Shape cloning seems to be good candidate for low hanging fruit optimizations:
- currently it always relies on heap allocations and since it happens many times per step it adds up quickly;
- it uses shared_ptr though shared ownership does not seem to be really required from the first look, perhaps price of atomic counters ticking may be avoided?

Since set of supported shapes is finite and static it may be worth trying replacing inheritance, heap allocs and shared ownership with smth stack-based and std::variant<shape1...,shapeN>-powered 

If ideas like above weren't dismissed before and if PRs are accepted I can give it a go if there's agreed way to measure baseline

**Comment by Tw1ddle** [comment]
Hi I was away from open source for a while, but back now. I haven't really optimized it at a low level or written any performance tests. I think there's a lot of room for improvement. Did you do anything with this in the end?

**Comment by Tw1ddle** [comment]
I expect (well, guess) more performance improvement might come from rewriting the software-based rasterization code rather than avoiding heap allocations. I'm not going to have time to work on optimizing it myself, so I'll close this.

If you had an application where you need really great/realtime performance I'd suggest implementing a new library that runs on GPU/using shaders. I'd be happy to contribute to a project like that.
